-- Nota: En Oracle, las bases de datos normalmente se crean usando DBCA o durante la instalación.
-- Este script asume que ya estás conectado a una instancia de base de datos Oracle existente.

-- Crear la tabla (esto debe hacerse después de conectarse como el usuario C##ubdproducto)
CREATE TABLE articulo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(100) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    stock NUMBER(10) NOT NULL
);

-- Insertar datos de ejemplo
INSERT INTO articulo (nombre, categoria, precio, stock) VALUES
('Laptop', 'Electrónica', 1200.00, 10),
('Smartphone', 'Electrónica', 800.00, 25),
('Tablet', 'Electrónica', 500.00, 15),
('Cámara', 'Fotografía', 600.00, 5),
('Auriculares', 'Accesorios', 150.00, 30);

-- Confirmar los cambios
COMMIT;

-- Procedimiento almacenado para insertar datos en la tabla
CREATE OR REPLACE PROCEDURE SP_insertar_articulo (
    p_nombre IN VARCHAR2,
    p_categoria IN VARCHAR2,
    p_precio IN NUMBER,
    p_stock IN NUMBER
) AS
BEGIN
    INSERT INTO articulo (nombre, categoria, precio, stock)
    VALUES (p_nombre, p_categoria, p_precio, p_stock);
END;

-- Usar el procedimiento almacenado
BEGIN
    SP_insertar_articulo('Producto E', 'Categoria A' , 50.00, 500);
END;

-- Probar el procedimiento almacenado usando CALL
CALL SP_insertar_articulo('Smartwatch', 'Electrónica', 200.00, 20);
